

version: '3.8'

services:
  moja_baza_danych:
    
    image: postgres:15
    
    environment:
      - POSTGRES_USER=bartek
      - POSTGRES_PASSWORD=haslo
      - POSTGRES_DB=pogoda_db
    ports:
      - "5433:5432"
  
  
  moj_skrypt_python:
    build: . 
   
    depends_on:
      - moja_baza_danych
